model = "F5TTS_Base"
ref_audio = "D:\\Files\\Internhips\\Zenyro Labs Tasks\\Zenyro Labs Voice Studio\\temp\\trimmed_ref_gen.wav"
ref_text = "This is a long audio recording designed to serve as a dataset for voice training."
speed = 1.0
nfe_step = 16
gen_text = "Hello there, this is the first line."
output_dir = "D:\\Files\\Internhips\\Zenyro Labs Tasks\\Zenyro Labs Voice Studio"
output_file = "podcast_line_0.wav"

[voices]
